language: c

sudo: required

services:
  - docker

before_install:
  - docker build -t redis-example . 
  - docker run -d -p 6379:6379 redis-example
  - docker container list

script:
 - make -C hiredis/
 - make -C tests/
 - ./tests/test-hgetset

#comment so I can recommit this file and try to trigger a Travis build
